# Generated by Django 6.1 on 2026-09-01 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкое'), ('medium', 'Среднее'), ('hard', 'Сложное')], default='easy', max_length=50, verbose_name='Сложность')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name='Имя экстренного контакта')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='Телефон экстренного контакта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProsthesisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hours_worn', models.FloatField(verbose_name='Часы ношения')),
                ('discomfort_level', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Уровень дискомфорта (1-10)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosthesis_logs', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.exercise')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='patients.patientprofile')),
            ],
            options={
                'unique_together': {('patient', 'exercise', 'date')},
            },
        ),
    ]
