# Generated by Django 6.1 on 2026-09-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_activity_emergencycontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prosthesislog',
            name='hours_worn',
        ),
        migrations.AddField(
            model_name='prosthesislog',
            name='minutes_worn',
            field=models.IntegerField(default=0, verbose_name='Минуты ношения'),
            preserve_default=False,
        ),
    ]
