# Generated by Django 6.1 on 2026-09-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_prosthesislog_hours_worn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='exercise',
            name='rehab_stage',
            field=models.CharField(choices=[('early', 'Ранний этап'), ('mid', 'Средний этап'), ('late', 'Поздний этап')], default='early', max_length=50, verbose_name='Этап реабилитации'),
        ),
    ]
