# Generated by Django 6.1 on 2026-09-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_exercise_difficulty_exercise_rehab_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rehab_stage',
            field=models.CharField(choices=[('early', 'Ранний'), ('mid', 'Средний'), ('late', 'Поздний')], default='early', max_length=50, verbose_name='Этап реабилитации'),
        ),
    ]
