# Generated by Django 6.1 on 2026-09-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientprofile_first_name_patientprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date'], 'verbose_name': 'Активность', 'verbose_name_plural': 'Активности'},
        ),
    ]
