# Generated by Django 6.1 on 2026-09-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_activity_options_exercise_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность (минут)'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='repetitions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество повторений'),
        ),
    ]
