# Generated by Django 6.1 on 2026-09-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_dailyplan_duration_minutes_dailyplan_repetitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
