# Generated by Django 6.1 on 2026-09-11 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_dailyplan_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplan',
            name='is_done',
        ),
        migrations.CreateModel(
            name='IsDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='patients.dailyplan')),
            ],
            options={
                'unique_together': {('daily_plan', 'date')},
            },
        ),
    ]
